version: "3.3"
services:
  app-casbin:
    image: node:12-slim
    working_dir: /app
    command: npm run dev
    networks:
      - backend 
    depends_on:
      - mongo-casbin
    ports:
      - 8080:8080
    volumes:
      - ./app/:/app/

  mongo-casbin:
    image: mongo:4.2.5
    networks:
      - backend
    volumes:
      - "./mongodb/data/:/data/db/"
    ports:
      - 27000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: pass123 
      MONGO_INITDB_DATABASE: casbin

networks:
  backend:
