version: "2.0"
services:
  app-casbin:
    image: node:12-slim
    working_dir: /app
    command: npm run dev
    networks:
      - backend 
    depends_on:
      - mongo-casbin
      - api-casbin
    ports:
      - 8080:80
    volumes:
      - ./app/:/app/

  api-casbin:
    image: node:12-slim
    working_dir: /app
    command: npm run dev
    networks:
      - backend 
    depends_on:
      - mongo-casbin
    ports:
      - 7080:80
    volumes:
      - ./api/:/app/

  mongo-casbin:
    image: mongo:4.2.5
    networks:
      - backend
    volumes:
      - "./mongodb/data/:/data/db/"
    ports:
      - 27000:27017
    environment:
      MONGO_INITDB_DATABASE: casbin
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: pass123 

networks:
  backend:
